// <auto-generated />
namespace Projeto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DBUP7WEBAPI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBUP7WEBAPI));
        
        string IMigrationMetadata.Id
        {
            get { return "201802171825300_DBUP7WEBAPI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
